// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

#include "enums.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_enums_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_enums_2eproto[84];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_enums_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_enums_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_enums_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013enums.proto*\360\n\n\027EPublishedFileQueryTyp"
  "e\022)\n%k_PublishedFileQueryType_RankedByVo"
  "te\020\000\0224\n0k_PublishedFileQueryType_RankedB"
  "yPublicationDate\020\001\022B\n>k_PublishedFileQue"
  "ryType_AcceptedForGameRankedByAcceptance"
  "Date\020\002\022*\n&k_PublishedFileQueryType_Ranke"
  "dByTrend\020\003\022F\nBk_PublishedFileQueryType_F"
  "avoritedByFriendsRankedByPublicationDate"
  "\020\004\022D\n@k_PublishedFileQueryType_CreatedBy"
  "FriendsRankedByPublicationDate\020\005\0225\n1k_Pu"
  "blishedFileQueryType_RankedByNumTimesRep"
  "orted\020\006\022J\nFk_PublishedFileQueryType_Crea"
  "tedByFollowedUsersRankedByPublicationDat"
  "e\020\007\022(\n$k_PublishedFileQueryType_NotYetRa"
  "ted\020\010\022=\n9k_PublishedFileQueryType_Ranked"
  "ByTotalUniqueSubscriptions\020\t\0222\n.k_Publis"
  "hedFileQueryType_RankedByTotalVotesAsc\020\n"
  "\022,\n(k_PublishedFileQueryType_RankedByVot"
  "esUp\020\013\022/\n+k_PublishedFileQueryType_Ranke"
  "dByTextSearch\020\014\0222\n.k_PublishedFileQueryT"
  "ype_RankedByPlaytimeTrend\020\r\0222\n.k_Publish"
  "edFileQueryType_RankedByTotalPlaytime\020\016\022"
  "9\n5k_PublishedFileQueryType_RankedByAver"
  "agePlaytimeTrend\020\017\022<\n8k_PublishedFileQue"
  "ryType_RankedByLifetimeAveragePlaytime\020\020"
  "\022:\n6k_PublishedFileQueryType_RankedByPla"
  "ytimeSessionsTrend\020\021\022=\n9k_PublishedFileQ"
  "ueryType_RankedByLifetimePlaytimeSession"
  "s\020\022\022\?\n;k_PublishedFileQueryType_RankedBy"
  "InappropriateContentRating\020\023\0224\n0k_Publis"
  "hedFileQueryType_RankedByBanContentCheck"
  "\020\024\0224\n0k_PublishedFileQueryType_RankedByL"
  "astUpdatedDate\020\025\0223\n/k_PublishedFileQuery"
  "Type_RankedByNumParentItems\020\026\0229\n5k_Publi"
  "shedFileQueryType_RankedByNumParentColle"
  "ctions\020\027*\274\001\n#EPublishedFileInappropriate"
  "Provider\0221\n-k_EPublishedFileInappropriat"
  "eProvider_Invalid\020\000\0220\n,k_EPublishedFileI"
  "nappropriateProvider_Google\020\001\0220\n,k_EPubl"
  "ishedFileInappropriateProvider_Amazon\020\002*"
  "\325\002\n!EPublishedFileInappropriateResult\0222\n"
  ".k_EPublishedFileInappropriateResult_Not"
  "Scanned\020\000\0224\n0k_EPublishedFileInappropria"
  "teResult_VeryUnlikely\020\001\0220\n,k_EPublishedF"
  "ileInappropriateResult_Unlikely\020\036\0220\n,k_E"
  "PublishedFileInappropriateResult_Possibl"
  "e\0202\022.\n*k_EPublishedFileInappropriateResu"
  "lt_Likely\020K\0222\n.k_EPublishedFileInappropr"
  "iateResult_VeryLikely\020d*\261\003\n\021EPersonaStat"
  "eFlag\022\'\n#k_EPersonaStateFlag_HasRichPres"
  "ence\020\001\022&\n\"k_EPersonaStateFlag_InJoinable"
  "Game\020\002\022\036\n\032k_EPersonaStateFlag_Golden\020\004\022*"
  "\n&k_EPersonaStateFlag_RemotePlayTogether"
  "\020\010\022&\n!k_EPersonaStateFlag_ClientTypeWeb\020"
  "\200\002\022)\n$k_EPersonaStateFlag_ClientTypeMobi"
  "le\020\200\004\022*\n%k_EPersonaStateFlag_ClientTypeT"
  "enfoot\020\200\010\022%\n k_EPersonaStateFlag_ClientT"
  "ypeVR\020\200\020\022*\n%k_EPersonaStateFlag_LaunchTy"
  "peGamepad\020\200 \022-\n(k_EPersonaStateFlag_Laun"
  "chTypeCompatTool\020\200@*\260\002\n\025EContentCheckPro"
  "vider\022#\n\037k_EContentCheckProvider_Invalid"
  "\020\000\022-\n)k_EContentCheckProvider_Google_DEP"
  "RECATED\020\001\022\"\n\036k_EContentCheckProvider_Ama"
  "zon\020\002\022!\n\035k_EContentCheckProvider_Local\020\003"
  "\022*\n&k_EContentCheckProvider_GoogleVertex"
  "AI\020\004\022(\n$k_EContentCheckProvider_GoogleGe"
  "mini\020\005\022&\n\"k_EContentCheckProvider_SteamL"
  "earn\020\006*\223\t\n\031EProfileCustomizationType\022&\n\""
  "k_EProfileCustomizationTypeInvalid\020\000\0226\n2"
  "k_EProfileCustomizationTypeRareAchieveme"
  "ntShowcase\020\001\022,\n(k_EProfileCustomizationT"
  "ypeGameCollector\020\002\022+\n\'k_EProfileCustomiz"
  "ationTypeItemShowcase\020\003\022,\n(k_EProfileCus"
  "tomizationTypeTradeShowcase\020\004\022%\n!k_EProf"
  "ileCustomizationTypeBadges\020\005\022+\n\'k_EProfi"
  "leCustomizationTypeFavoriteGame\020\006\0221\n-k_E"
  "ProfileCustomizationTypeScreenshotShowca"
  "se\020\007\022)\n%k_EProfileCustomizationTypeCusto"
  "mText\020\010\022,\n(k_EProfileCustomizationTypeFa"
  "voriteGroup\020\t\022-\n)k_EProfileCustomization"
  "TypeRecommendation\020\n\022+\n\'k_EProfileCustom"
  "izationTypeWorkshopItem\020\013\022)\n%k_EProfileC"
  "ustomizationTypeMyWorkshop\020\014\022.\n*k_EProfi"
  "leCustomizationTypeArtworkShowcase\020\r\022,\n("
  "k_EProfileCustomizationTypeVideoShowcase"
  "\020\016\022%\n!k_EProfileCustomizationTypeGuides\020"
  "\017\022\'\n#k_EProfileCustomizationTypeMyGuides"
  "\020\020\022+\n\'k_EProfileCustomizationTypeAchieve"
  "ments\020\021\022)\n%k_EProfileCustomizationTypeGr"
  "eenlight\020\022\022+\n\'k_EProfileCustomizationTyp"
  "eMyGreenlight\020\023\022%\n!k_EProfileCustomizati"
  "onTypeSalien\020\024\0225\n1k_EProfileCustomizatio"
  "nTypeLoyaltyRewardReactions\020\025\0224\n0k_EProf"
  "ileCustomizationTypeSingleArtworkShowcas"
  "e\020\026\0228\n4k_EProfileCustomizationTypeAchiev"
  "ementsCompletionist\020\027\022%\n!k_EProfileCusto"
  "mizationTypeReplay\020\030*\310\001\n\033EPublishedFileS"
  "torageSystem\022(\n$k_EPublishedFileStorageS"
  "ystemInvalid\020\000\022,\n(k_EPublishedFileStorag"
  "eSystemLegacyCloud\020\001\022&\n\"k_EPublishedFile"
  "StorageSystemDepot\020\002\022)\n%k_EPublishedFile"
  "StorageSystemUGCCloud\020\003*\227\001\n\031ECloudStorag"
  "ePersistState\022(\n$k_ECloudStoragePersistS"
  "tatePersisted\020\000\022(\n$k_ECloudStoragePersis"
  "tStateForgotten\020\001\022&\n\"k_ECloudStoragePers"
  "istStateDeleted\020\002*\350\001\n\022ESDCardFormatStage"
  "\022 \n\034k_ESDCardFormatStage_Invalid\020\000\022!\n\035k_"
  "ESDCardFormatStage_Starting\020\001\022 \n\034k_ESDCa"
  "rdFormatStage_Testing\020\002\022!\n\035k_ESDCardForm"
  "atStage_Rescuing\020\003\022#\n\037k_ESDCardFormatSta"
  "ge_Formatting\020\004\022#\n\037k_ESDCardFormatStage_"
  "Finalizing\020\005*\225\002\n\023EStorageFormatStage\022!\n\035"
  "k_EStorageFormatStage_Invalid\020\000\022$\n k_ESt"
  "orageFormatStage_NotRunning\020\001\022\"\n\036k_EStor"
  "ageFormatStage_Starting\020\002\022!\n\035k_EStorageF"
  "ormatStage_Testing\020\003\022\"\n\036k_EStorageFormat"
  "Stage_Rescuing\020\004\022$\n k_EStorageFormatStag"
  "e_Formatting\020\005\022$\n k_EStorageFormatStage_"
  "Finalizing\020\006*\204\001\n\025ESystemFanControlMode\022\""
  "\n\036k_SystemFanControlMode_Invalid\020\000\022#\n\037k_"
  "SystemFanControlMode_Disabled\020\001\022\"\n\036k_Sys"
  "temFanControlMode_Default\020\002*\213\001\n\023EColorGa"
  "mutLabelSet\022 \n\034k_ColorGamutLabelSet_Defa"
  "ult\020\000\022$\n k_ColorGamutLabelSet_sRGB_Nativ"
  "e\020\001\022,\n(k_ColorGamutLabelSet_Native_sRGB_"
  "Boosted\020\002*}\n\024EWindowStackingOrder\022\"\n\036k_E"
  "WindowStackingOrder_Invalid\020\000\022\036\n\032k_EWind"
  "owStackingOrder_Top\020\001\022!\n\035k_EWindowStacki"
  "ngOrder_Bottom\020\002*\300\003\n\024EBluetoothDeviceTyp"
  "e\022!\n\035k_BluetoothDeviceType_Invalid\020\000\022!\n\035"
  "k_BluetoothDeviceType_Unknown\020\001\022\037\n\033k_Blu"
  "etoothDeviceType_Phone\020\002\022\"\n\036k_BluetoothD"
  "eviceType_Computer\020\003\022!\n\035k_BluetoothDevic"
  "eType_Headset\020\004\022$\n k_BluetoothDeviceType"
  "_Headphones\020\005\022\"\n\036k_BluetoothDeviceType_S"
  "peakers\020\006\022$\n k_BluetoothDeviceType_Other"
  "Audio\020\007\022\037\n\033k_BluetoothDeviceType_Mouse\020\010"
  "\022\"\n\036k_BluetoothDeviceType_Joystick\020\t\022!\n\035"
  "k_BluetoothDeviceType_Gamepad\020\n\022\"\n\036k_Blu"
  "etoothDeviceType_Keyboard\020\013*\302\001\n\025ESpeaker"
  "Configuration\022!\n\035k_ESpeakerConfiguration"
  "_Other\020\000\022\"\n\036k_ESpeakerConfiguration_Ster"
  "eo\020\001\022\036\n\032k_ESpeakerConfiguration_51\020\002\022\036\n\032"
  "k_ESpeakerConfiguration_71\020\003\022\"\n\036k_ESpeak"
  "erConfiguration_51_Ac3\020\004*\200\001\n\025ESystemAudi"
  "oDirection\022\"\n\036k_SystemAudioDirection_Inv"
  "alid\020\000\022 \n\034k_SystemAudioDirection_Input\020\001"
  "\022!\n\035k_SystemAudioDirection_Output\020\002*\361\002\n\023"
  "ESystemAudioChannel\022 \n\034k_SystemAudioChan"
  "nel_Invalid\020\000\022#\n\037k_SystemAudioChannel_Ag"
  "gregated\020\001\022\"\n\036k_SystemAudioChannel_Front"
  "Left\020\002\022#\n\037k_SystemAudioChannel_FrontRigh"
  "t\020\003\022\034\n\030k_SystemAudioChannel_LFE\020\004\022!\n\035k_S"
  "ystemAudioChannel_BackLeft\020\005\022\"\n\036k_System"
  "AudioChannel_BackRight\020\006\022$\n k_SystemAudi"
  "oChannel_FrontCenter\020\007\022 \n\034k_SystemAudioC"
  "hannel_Unknown\020\010\022\035\n\031k_SystemAudioChannel"
  "_Mono\020\t*\311\001\n\024ESystemAudioPortType\022!\n\035k_Sy"
  "stemAudioPortType_Invalid\020\000\022!\n\035k_SystemA"
  "udioPortType_Unknown\020\001\022\"\n\036k_SystemAudioP"
  "ortType_Audio32f\020\002\022 \n\034k_SystemAudioPortT"
  "ype_Midi8b\020\003\022%\n!k_SystemAudioPortType_Vi"
  "deo32RGBA\020\004*\220\001\n\031ESystemAudioPortDirectio"
  "n\022&\n\"k_SystemAudioPortDirection_Invalid\020"
  "\000\022$\n k_SystemAudioPortDirection_Input\020\001\022"
  "%\n!k_SystemAudioPortDirection_Output\020\002*\203"
  "\001\n\023ESystemServiceState\022%\n!k_ESystemServi"
  "ceState_Unavailable\020\000\022\"\n\036k_ESystemServic"
  "eState_Disabled\020\001\022!\n\035k_ESystemServiceSta"
  "te_Enabled\020\002*m\n\031EBluetoothAudioPreferenc"
  "e\022\'\n#k_EBluetoothAudioPreference_Quality"
  "\020\000\022\'\n#k_EBluetoothAudioPreference_Latenc"
  "y\020\001*\341\001\n\031EGraphicsPerfOverlayLevel\022&\n\"k_E"
  "GraphicsPerfOverlayLevel_Hidden\020\000\022%\n!k_E"
  "GraphicsPerfOverlayLevel_Basic\020\001\022&\n\"k_EG"
  "raphicsPerfOverlayLevel_Medium\020\002\022$\n k_EG"
  "raphicsPerfOverlayLevel_Full\020\003\022\'\n#k_EGra"
  "phicsPerfOverlayLevel_Minimal\020\004*\345\001\n\024EGPU"
  "PerformanceLevel\022\"\n\036k_EGPUPerformanceLev"
  "el_Invalid\020\000\022\037\n\033k_EGPUPerformanceLevel_A"
  "uto\020\001\022!\n\035k_EGPUPerformanceLevel_Manual\020\002"
  "\022\036\n\032k_EGPUPerformanceLevel_Low\020\003\022\037\n\033k_EG"
  "PUPerformanceLevel_High\020\004\022$\n k_EGPUPerfo"
  "rmanceLevel_Profiling\020\005*\310\001\n\023ESplitScalin"
  "gFilter\022!\n\035k_ESplitScalingFilter_Invalid"
  "\020\000\022 \n\034k_ESplitScalingFilter_Linear\020\001\022!\n\035"
  "k_ESplitScalingFilter_Nearest\020\002\022\037\n\033k_ESp"
  "litScalingFilter_Sharp\020\003\022(\n$k_ESplitScal"
  "ingFilter_NIS_Deprecated\020\004*\335\001\n\023ESplitSca"
  "lingScaler\022!\n\035k_ESplitScalingScaler_Inva"
  "lid\020\000\022\036\n\032k_ESplitScalingScaler_Auto\020\001\022!\n"
  "\035k_ESplitScalingScaler_Integer\020\002\022\035\n\031k_ES"
  "plitScalingScaler_Fit\020\003\022\036\n\032k_ESplitScali"
  "ngScaler_Fill\020\004\022!\n\035k_ESplitScalingScaler"
  "_Stretch\020\005*}\n\022EGamescopeBlurMode\022!\n\035k_EG"
  "amescopeBlurMode_Disabled\020\000\022#\n\037k_EGamesc"
  "opeBlurMode_IfOccluded\020\001\022\037\n\033k_EGamescope"
  "BlurMode_Always\020\002*\304\001\n\nESLSHelper\022\030\n\024k_ES"
  "LSHelper_Invalid\020\000\022\031\n\025k_ESLSHelper_Minid"
  "ump\020\001\022\026\n\022k_ESLSHelper_Kdump\020\002\022\030\n\024k_ESLSH"
  "elper_Journal\020\003\022\024\n\020k_ESLSHelper_Gpu\020\004\022\033\n"
  "\027k_ESLSHelper_SystemInfo\020\005\022\034\n\030k_ESLSHelp"
  "er_Devcoredump\020\006*\305\001\n\021EHDRVisualization\022\034"
  "\n\030k_EHDRVisualization_None\020\000\022\037\n\033k_EHDRVi"
  "sualization_Heatmap\020\001\022 \n\034k_EHDRVisualiza"
  "tion_Analysis\020\002\022\'\n#k_EHDRVisualization_H"
  "eatmapExtended\020\003\022&\n\"k_EHDRVisualization_"
  "HeatmapClassic\020\004*\201\001\n\023EHDRToneMapOperator"
  "\022!\n\035k_EHDRToneMapOperator_Invalid\020\000\022#\n\037k"
  "_EHDRToneMapOperator_Uncharted\020\001\022\"\n\036k_EH"
  "DRToneMapOperator_Reinhard\020\002*|\n\014ECPUGove"
  "rnor\022\032\n\026k_ECPUGovernor_Invalid\020\000\022\027\n\023k_EC"
  "PUGovernor_Perf\020\001\022\034\n\030k_ECPUGovernor_Powe"
  "rsave\020\002\022\031\n\025k_ECPUGovernor_Manual\020\003*\342\001\n\014E"
  "UpdaterType\022\032\n\026k_EUpdaterType_Invalid\020\000\022"
  "\031\n\025k_EUpdaterType_Client\020\001\022\025\n\021k_EUpdater"
  "Type_OS\020\002\022\027\n\023k_EUpdaterType_BIOS\020\003\022\035\n\031k_"
  "EUpdaterType_Aggregated\020\004\022\030\n\024k_EUpdaterT"
  "ype_Test1\020\005\022\030\n\024k_EUpdaterType_Test2\020\006\022\030\n"
  "\024k_EUpdaterType_Dummy\020\007*\227\002\n\rEUpdaterStat"
  "e\022\033\n\027k_EUpdaterState_Invalid\020\000\022\034\n\030k_EUpd"
  "aterState_UpToDate\020\002\022\034\n\030k_EUpdaterState_"
  "Checking\020\003\022\035\n\031k_EUpdaterState_Available\020"
  "\004\022\034\n\030k_EUpdaterState_Applying\020\005\022(\n$k_EUp"
  "daterState_ClientRestartPending\020\006\022(\n$k_E"
  "UpdaterState_SystemRestartPending\020\007\022\034\n\030k"
  "_EUpdaterState_RollBack\020\010*\341\001\n\030EStorageBl"
  "ockContentType\022&\n\"k_EStorageBlockContent"
  "Type_Invalid\020\000\022&\n\"k_EStorageBlockContent"
  "Type_Unknown\020\001\022)\n%k_EStorageBlockContent"
  "Type_FileSystem\020\002\022%\n!k_EStorageBlockCont"
  "entType_Crypto\020\003\022#\n\037k_EStorageBlockConte"
  "ntType_Raid\020\004*\303\001\n\033EStorageBlockFileSyste"
  "mType\022)\n%k_EStorageBlockFileSystemType_I"
  "nvalid\020\000\022)\n%k_EStorageBlockFileSystemTyp"
  "e_Unknown\020\001\022&\n\"k_EStorageBlockFileSystem"
  "Type_VFat\020\002\022&\n\"k_EStorageBlockFileSystem"
  "Type_Ext4\020\003*\320\001\n\026EStorageDriveMediaType\022$"
  "\n k_EStorageDriveMediaType_Invalid\020\000\022$\n "
  "k_EStorageDriveMediaType_Unknown\020\001\022 \n\034k_"
  "EStorageDriveMediaType_HDD\020\002\022 \n\034k_EStora"
  "geDriveMediaType_SSD\020\003\022&\n\"k_EStorageDriv"
  "eMediaType_Removable\020\004*\263\001\n\037ESystemDispla"
  "yCompatibilityMode\022-\n)k_ESystemDisplayCo"
  "mpatibilityMode_Invalid\020\000\022*\n&k_ESystemDi"
  "splayCompatibilityMode_None\020\001\0225\n1k_ESyst"
  "emDisplayCompatibilityMode_MinimalBandwi"
  "th\020\002*\255\001\n\035ESteamOSCompatibilityCategory\022+"
  "\n\'k_ESteamOSCompatibilityCategory_Unknow"
  "n\020\000\022/\n+k_ESteamOSCompatibilityCategory_U"
  "nsupported\020\001\022.\n*k_ESteamOSCompatibilityC"
  "ategory_Compatible\020\002*\217\002\n&ESteamOSCompati"
  "bilityResultDisplayType\0226\n2k_ESteamOSCom"
  "patibilityResultDisplayType_Invisible\020\000\022"
  ":\n6k_ESteamOSCompatibilityResultDisplayT"
  "ype_Informational\020\001\0228\n4k_ESteamOSCompati"
  "bilityResultDisplayType_Unsupported\020\002\0227\n"
  "3k_ESteamOSCompatibilityResultDisplayTyp"
  "e_Compatible\020\003*\343\001\n\037ESteamDeckCompatibili"
  "tyCategory\022-\n)k_ESteamDeckCompatibilityC"
  "ategory_Unknown\020\000\0221\n-k_ESteamDeckCompati"
  "bilityCategory_Unsupported\020\001\022.\n*k_ESteam"
  "DeckCompatibilityCategory_Playable\020\002\022.\n*"
  "k_ESteamDeckCompatibilityCategory_Verifi"
  "ed\020\003*\320\002\n(ESteamDeckCompatibilityResultDi"
  "splayType\0228\n4k_ESteamDeckCompatibilityRe"
  "sultDisplayType_Invisible\020\000\022<\n8k_ESteamD"
  "eckCompatibilityResultDisplayType_Inform"
  "ational\020\001\022:\n6k_ESteamDeckCompatibilityRe"
  "sultDisplayType_Unsupported\020\002\0227\n3k_EStea"
  "mDeckCompatibilityResultDisplayType_Play"
  "able\020\003\0227\n3k_ESteamDeckCompatibilityResul"
  "tDisplayType_Verified\020\004*\232\002\n!ESteamDeckCo"
  "mpatibilityTestResult\022/\n+k_ESteamDeckCom"
  "patibilityTestResult_Invalid\020\000\0225\n1k_ESte"
  "amDeckCompatibilityTestResult_NotApplica"
  "ble\020\001\022,\n(k_ESteamDeckCompatibilityTestRe"
  "sult_Pass\020\002\022,\n(k_ESteamDeckCompatibility"
  "TestResult_Fail\020\003\0221\n-k_ESteamDeckCompati"
  "bilityTestResult_FailMinor\020\004*w\n\010EACState"
  "\022\026\n\022k_EACState_Unknown\020\000\022\033\n\027k_EACState_D"
  "isconnected\020\001\022\030\n\024k_EACState_Connected\020\002\022"
  "\034\n\030k_EACState_ConnectedSlow\020\003*\205\001\n\rEBatte"
  "ryState\022\033\n\027k_EBatteryState_Unknown\020\000\022\037\n\033"
  "k_EBatteryState_Discharging\020\001\022\034\n\030k_EBatt"
  "eryState_Charging\020\002\022\030\n\024k_EBatteryState_F"
  "ull\020\003*\376\001\n\tEOSBranch\022\027\n\023k_EOSBranch_Unkno"
  "wn\020\000\022\027\n\023k_EOSBranch_Release\020\001\022 \n\034k_EOSBr"
  "anch_ReleaseCandidate\020\002\022\024\n\020k_EOSBranch_B"
  "eta\020\003\022\035\n\031k_EOSBranch_BetaCandidate\020\004\022\027\n\023"
  "k_EOSBranch_Preview\020\005\022 \n\034k_EOSBranch_Pre"
  "viewCandidate\020\006\022\024\n\020k_EOSBranch_Main\020\007\022\027\n"
  "\023k_EOSBranch_Staging\020\010*\306\003\n\021EBrowserGPUSt"
  "atus\022\037\n\033k_EBrowserGPUStatus_Invalid\020\000\022\037\n"
  "\033k_EBrowserGPUStatus_Enabled\020\001\022\'\n#k_EBro"
  "wserGPUStatus_DisabledUnknown\020\002\022*\n&k_EBr"
  "owserGPUStatus_DisabledCrashCount\020\004\022)\n%k"
  "_EBrowserGPUStatus_DisabledBlocklist\020\005\022)"
  "\n%k_EBrowserGPUStatus_DisabledJSRequest\020"
  "\006\022+\n\'k_EBrowserGPUStatus_DisabledCommand"
  "Line\020\007\022-\n)k_EBrowserGPUStatus_DisabledRu"
  "ntimeDetect\020\010\0220\n,k_EBrowserGPUStatus_Dis"
  "abledChildCommandLine\020\t\0226\n2k_EBrowserGPU"
  "Status_DisabledCompositingCommandLine\020\n*"
  "\343\004\n\025EBrowserFeatureStatus\022#\n\037k_EBrowserF"
  "eatureStatus_Invalid\020\000\022$\n k_EBrowserFeat"
  "ureStatus_NotFound\020\001\022#\n\037k_EBrowserFeatur"
  "eStatus_Unknown\020\002\022,\n(k_EBrowserFeatureSt"
  "atus_DisabledSoftware\020\003\022\'\n#k_EBrowserFea"
  "tureStatus_DisabledOff\020\004\022)\n%k_EBrowserFe"
  "atureStatus_DisabledOffOk\020\005\022/\n+k_EBrowse"
  "rFeatureStatus_UnavailableSoftware\020\006\022*\n&"
  "k_EBrowserFeatureStatus_UnavailableOff\020\007"
  "\022,\n(k_EBrowserFeatureStatus_UnavailableO"
  "ffOk\020\010\022+\n\'k_EBrowserFeatureStatus_Enable"
  "dReadback\020\t\022(\n$k_EBrowserFeatureStatus_E"
  "nabledForce\020\n\022#\n\037k_EBrowserFeatureStatus"
  "_Enabled\020\013\022%\n!k_EBrowserFeatureStatus_En"
  "abledOn\020\014\022*\n&k_EBrowserFeatureStatus_Ena"
  "bledForceOn\020\r*\237\005\n\014EGpuDriverId\022\032\n\026k_EGpu"
  "DriverId_Invalid\020\000\022\032\n\026k_EGpuDriverId_Unk"
  "nown\020\001\022!\n\035k_EGpuDriverId_AmdProprietary\020"
  "\002\022 \n\034k_EGpuDriverId_AmdOpenSource\020\003\022\033\n\027k"
  "_EGpuDriverId_MesaRadv\020\004\022$\n k_EGpuDriver"
  "Id_NvidiaProprietary\020\005\022\"\n\036k_EGpuDriverId"
  "_IntelPropietary\020\006\022\034\n\030k_EGpuDriverId_Mes"
  "aIntel\020\007\022&\n\"k_EGpuDriverId_QualcommPropr"
  "ietary\020\010\022!\n\035k_EGpuDriverId_ArmProprietar"
  "y\020\t\022$\n k_EGpuDriverId_GoogleSwiftshader\020"
  "\n\022&\n\"k_EGpuDriverId_BroadcomProprietary\020"
  "\013\022\037\n\033k_EGpuDriverId_MesaLLVMPipe\020\014\022\033\n\027k_"
  "EGpuDriverId_MoltenVK\020\r\022\035\n\031k_EGpuDriverI"
  "d_MesaTurnip\020\016\022\034\n\030k_EGpuDriverId_MesaPan"
  "VK\020\017\022\034\n\030k_EGpuDriverId_MesaVenus\020\020\022\034\n\030k_"
  "EGpuDriverId_MesaDozen\020\021\022\032\n\026k_EGpuDriver"
  "Id_MesaNVK\020\022\022!\n\035k_EGpuDriverId_MesaHoney"
  "Krisp\020\023*\335\005\n\023ECommunityItemClass\022!\n\035k_ECo"
  "mmunityItemClass_Invalid\020\000\022\037\n\033k_ECommuni"
  "tyItemClass_Badge\020\001\022\"\n\036k_ECommunityItemC"
  "lass_GameCard\020\002\022+\n\'k_ECommunityItemClass"
  "_ProfileBackground\020\003\022\"\n\036k_ECommunityItem"
  "Class_Emoticon\020\004\022%\n!k_ECommunityItemClas"
  "s_BoosterPack\020\005\022$\n k_ECommunityItemClass"
  "_Consumable\020\006\022!\n\035k_ECommunityItemClass_G"
  "ameGoo\020\007\022)\n%k_ECommunityItemClass_Profil"
  "eModifier\020\010\022\037\n\033k_ECommunityItemClass_Sce"
  "ne\020\t\022$\n k_ECommunityItemClass_SalienItem"
  "\020\n\022!\n\035k_ECommunityItemClass_Sticker\020\013\022$\n"
  " k_ECommunityItemClass_ChatEffect\020\014\022/\n+k"
  "_ECommunityItemClass_MiniProfileBackgrou"
  "nd\020\r\022%\n!k_ECommunityItemClass_AvatarFram"
  "e\020\016\022(\n$k_ECommunityItemClass_AnimatedAva"
  "tar\020\017\022/\n+k_ECommunityItemClass_SteamDeck"
  "KeyboardSkin\020\020\022/\n+k_ECommunityItemClass_"
  "SteamDeckStartupMovie\020\021*\331\001\n\037ESteamDeckCo"
  "mpatibilityFeedback\022+\n\'k_ESteamDeckCompa"
  "tibilityFeedback_Unset\020\000\022+\n\'k_ESteamDeck"
  "CompatibilityFeedback_Agree\020\001\022.\n*k_EStea"
  "mDeckCompatibilityFeedback_Disagree\020\002\022,\n"
  "(k_ESteamDeckCompatibilityFeedback_Ignor"
  "e\020\003*\237\001\n\036EProvideDeckFeedbackPreference\022*"
  "\n&k_EProvideDeckFeedbackPreference_Unset"
  "\020\000\022(\n$k_EProvideDeckFeedbackPreference_Y"
  "es\020\001\022\'\n#k_EProvideDeckFeedbackPreference"
  "_No\020\002*\350\002\n%EHardwareCompatibilityFeedback"
  "Details\0221\n-k_EHardwareCompatibilityFeedb"
  "ackDetails_Unset\020\000\0227\n3k_EHardwareCompati"
  "bilityFeedbackDetails_Performance\020\001\0225\n1k"
  "_EHardwareCompatibilityFeedbackDetails_S"
  "tability\020\002\0226\n2k_EHardwareCompatibilityFe"
  "edbackDetails_Legibility\020\004\0221\n-k_EHardwar"
  "eCompatibilityFeedbackDetails_Input\020\010\0221\n"
  "-k_EHardwareCompatibilityFeedbackDetails"
  "_Other\020\020*\357\001\n!EGameFrameRateReportingPref"
  "erence\022-\n)k_EGameFrameRateReportingPrefe"
  "rence_Unset\020\000\022*\n&k_EGameFrameRateReporti"
  "ngPreference_No\020\001\0225\n1k_EGameFrameRateRep"
  "ortingPreference_Yes_Anonymous\020\002\0228\n4k_EG"
  "ameFrameRateReportingPreference_Yes_NonA"
  "nonymous\020\003*\261\003\n\rETouchGesture\022\027\n\023k_ETouch"
  "GestureNone\020\000\022\030\n\024k_ETouchGestureTouch\020\001\022"
  "\026\n\022k_ETouchGestureTap\020\002\022\034\n\030k_ETouchGestu"
  "reDoubleTap\020\003\022\035\n\031k_ETouchGestureShortPre"
  "ss\020\004\022\034\n\030k_ETouchGestureLongPress\020\005\022\032\n\026k_"
  "ETouchGestureLongTap\020\006\022\037\n\033k_ETouchGestur"
  "eTwoFingerTap\020\007\022\037\n\033k_ETouchGestureTapCan"
  "celled\020\010\022\035\n\031k_ETouchGesturePinchBegin\020\t\022"
  "\036\n\032k_ETouchGesturePinchUpdate\020\n\022\033\n\027k_ETo"
  "uchGesturePinchEnd\020\013\022\035\n\031k_ETouchGestureF"
  "lingStart\020\014\022!\n\035k_ETouchGestureFlingCance"
  "lled\020\r*\214\001\n\023ESessionPersistence\022*\n\035k_ESes"
  "sionPersistence_Invalid\020\377\377\377\377\377\377\377\377\377\001\022#\n\037k_"
  "ESessionPersistence_Ephemeral\020\000\022$\n k_ESe"
  "ssionPersistence_Persistent\020\001*\331\001\n\032ENewSt"
  "eamAnnouncementState\022(\n$k_ENewSteamAnnou"
  "ncementState_Invalid\020\000\022(\n$k_ENewSteamAnn"
  "ouncementState_AllRead\020\001\0220\n,k_ENewSteamA"
  "nnouncementState_NewAnnouncement\020\002\0225\n1k_"
  "ENewSteamAnnouncementState_FeaturedAnnou"
  "ncement\020\003*\376\001\n\nEForumType\022\030\n\024k_EForumType"
  "_Invalid\020\000\022\030\n\024k_EForumType_General\020\001\022\036\n\032"
  "k_EForumType_ReportedPosts\020\002\022\031\n\025k_EForum"
  "Type_Workshop\020\003\022\036\n\032k_EForumType_Publishe"
  "dFile\020\004\022\030\n\024k_EForumType_Trading\020\005\022\031\n\025k_E"
  "ForumType_PlayTest\020\006\022\026\n\022k_EForumType_Eve"
  "nt\020\007\022\024\n\020k_EForumType_Max\020\010*\213\007\n\022ECommentT"
  "hreadType\022\037\n\033k_ECommentThreadTypeInvalid"
  "\020\000\022-\n)k_ECommentThreadTypeScreenshot_Dep"
  "recated\020\001\0221\n-k_ECommentThreadTypeWorksho"
  "pAccount_Developer\020\002\022.\n*k_ECommentThread"
  "TypeWorkshopAccount_Public\020\003\022/\n+k_EComme"
  "ntThreadTypePublishedFile_Developer\020\004\022,\n"
  "(k_ECommentThreadTypePublishedFile_Publi"
  "c\020\005\022\034\n\030k_ECommentThreadTypeTest\020\006\022\"\n\036k_E"
  "CommentThreadTypeForumTopic\020\007\022&\n\"k_EComm"
  "entThreadTypeRecommendation\020\010\022(\n$k_EComm"
  "entThreadTypeVideo_Deprecated\020\t\022\037\n\033k_ECo"
  "mmentThreadTypeProfile\020\n\022 \n\034k_ECommentTh"
  "readTypeNewsPost\020\013\022\034\n\030k_ECommentThreadTy"
  "peClan\020\014\022(\n$k_ECommentThreadTypeClanAnno"
  "uncement\020\r\022!\n\035k_ECommentThreadTypeClanEv"
  "ent\020\016\022+\n\'k_ECommentThreadTypeUserStatusP"
  "ublished\020\017\022+\n\'k_ECommentThreadTypeUserRe"
  "ceivedNewGame\020\020\0222\n.k_ECommentThreadTypeP"
  "ublishedFile_Announcement\020\021\022(\n$k_ECommen"
  "tThreadTypeModeratorMessage\020\022\022&\n\"k_EComm"
  "entThreadTypeClanCuratedApp\020\023\022$\n k_EComm"
  "entThreadTypeQAndASession\020\024\022\033\n\027k_ECommen"
  "tThreadTypeMax\020\025*\327\001\n\024EBroadcastPermissio"
  "n\022\"\n\036k_EBroadcastPermissionDisabled\020\000\022(\n"
  "$k_EBroadcastPermissionFriendsApprove\020\001\022"
  "(\n$k_EBroadcastPermissionFriendsAllowed\020"
  "\002\022 \n\034k_EBroadcastPermissionPublic\020\003\022%\n!k"
  "_EBroadcastPermissionSubscribers\020\004*f\n\030EB"
  "roadcastEncoderSetting\022\"\n\036k_EBroadcastEn"
  "coderBestQuality\020\000\022&\n\"k_EBroadcastEncode"
  "rBestPerformance\020\001*y\n\024ECloudGamingPlatfo"
  "rm\022\036\n\032k_ECloudGamingPlatformNone\020\000\022\037\n\033k_"
  "ECloudGamingPlatformValve\020\001\022 \n\034k_ECloudG"
  "amingPlatformNVIDIA\020\002*\355\002\n\030ECompromiseDet"
  "ectionType\022#\n\037k_ECompromiseDetectionType"
  "_None\020\000\022)\n%k_ECompromiseDetectionType_Tr"
  "adeEvent\020\001\022*\n&k_ECompromiseDetectionType"
  "_ApiCallRate\020\002\022%\n!k_ECompromiseDetection"
  "Type_Manual\020\003\022+\n\'k_ECompromiseDetectionT"
  "ype_TicketAction\020\004\022.\n*k_ECompromiseDetec"
  "tionType_MaliciousRefund\020\005\022&\n\"k_EComprom"
  "iseDetectionType_Move2FA\020\006\022)\n%k_EComprom"
  "iseDetectionType_DeviceType\020\007*\326\001\n\032EAsync"
  "GameSessionUserState\0220\n#k_EAsyncGameSess"
  "ionUserStateUnknown\020\377\377\377\377\377\377\377\377\377\001\0220\n,k_EAsy"
  "ncGameSessionUserStateWaitingForOthers\020\000"
  "\022.\n*k_EAsyncGameSessionUserStateReadyFor"
  "Action\020\001\022$\n k_EAsyncGameSessionUserState"
  "Done\020\002*\304\001\n\037EAsyncGameSessionUserVisibili"
  "ty\022;\n7k_EAsyncGameSessionUserVisibilityE"
  "nvelopeAndSessionList\020\000\0224\n0k_EAsyncGameS"
  "essionUserVisibilitySessionListOnly\020\001\022.\n"
  "*k_EAsyncGameSessionUserVisibilityDismis"
  "sed\020\002*\324\001\n\022EGameRecordingType\022 \n\034k_EGameR"
  "ecordingType_Unknown\020\000\022%\n!k_EGameRecordi"
  "ngType_NotRecording\020\001\022(\n$k_EGameRecordin"
  "gType_ManualRecording\020\002\022,\n(k_EGameRecord"
  "ingType_BackgroundRecording\020\003\022\035\n\031k_EGame"
  "RecordingType_Clip\020\004*J\n\007EGRMode\022\023\n\017k_EGR"
  "Mode_Never\020\000\022\024\n\020k_EGRMode_Always\020\001\022\024\n\020k_"
  "EGRMode_Manual\020\002*\\\n\014EExportCodec\022\032\n\026k_EE"
  "xportCodec_Default\020\000\022\027\n\023k_EExportCodec_H"
  "264\020\001\022\027\n\023k_EExportCodec_H265\020\002*\352\003\n\rEProt"
  "oAppType\022\025\n\021k_EAppTypeInvalid\020\000\022\022\n\016k_EAp"
  "pTypeGame\020\001\022\031\n\025k_EAppTypeApplication\020\002\022\022"
  "\n\016k_EAppTypeTool\020\004\022\022\n\016k_EAppTypeDemo\020\010\022\027"
  "\n\023k_EAppTypeDeprected\020\020\022\021\n\rk_EAppTypeDLC"
  "\020 \022\023\n\017k_EAppTypeGuide\020@\022\025\n\020k_EAppTypeDri"
  "ver\020\200\001\022\025\n\020k_EAppTypeConfig\020\200\002\022\027\n\022k_EAppT"
  "ypeHardware\020\200\004\022\030\n\023k_EAppTypeFranchise\020\200\010"
  "\022\024\n\017k_EAppTypeVideo\020\200\020\022\025\n\020k_EAppTypePlug"
  "in\020\200 \022\031\n\024k_EAppTypeMusicAlbum\020\200@\022\026\n\020k_EA"
  "ppTypeSeries\020\200\200\001\022\025\n\017k_EAppTypeComic\020\200\200\002\022"
  "\024\n\016k_EAppTypeBeta\020\200\200\004\022\032\n\022k_EAppTypeShort"
  "cut\020\200\200\200\200\004\022 \n\023k_EAppTypeDepotOnly\020\200\200\200\200\370\377\377"
  "\377\377\001*\211\003\n\014EAppTestType\022\036\n\032k_EAppTestType_B"
  "uildReview\020\000\022\"\n\036k_EAppTestType_StorePage"
  "Review\020\001\022)\n%k_EAppTestType_SteamChina_Bu"
  "ildReview\020\002\022-\n)k_EAppTestType_SteamChina"
  "_StorePageReview\020\003\022=\n9k_EAppTestType_Ste"
  "amChinaPlatformOperator_StorePageReview\020"
  "\004\0229\n5k_EAppTestType_SteamChinaPlatformOp"
  "erator_BuildReview\020\005\022/\n+k_EAppTestType_S"
  "teamDeckCompatibilityReview\020\006\0220\n,k_EAppT"
  "estType_SteamFrameCompatibilityReview\020\007*"
  "\366\002\n\032EChildProcessQueryExitCode\022(\n$k_EChi"
  "ldProcessQueryExitCode_Success\020\000\022:\n-k_EC"
  "hildProcessQueryExitCode_ErrorCommandlin"
  "e\020\377\377\377\377\377\377\377\377\377\001\0224\n\'k_EChildProcessQueryExit"
  "Code_ErrorOther\020\376\377\377\377\377\377\377\377\377\001\022<\n/k_EChildPr"
  "ocessQueryExitCode_ErrorUnimplemented\020\375\377"
  "\377\377\377\377\377\377\377\001\0227\n*k_EChildProcessQueryExitCode"
  "_ErrorFileSave\020\374\377\377\377\377\377\377\377\377\001\022E\n8k_EChildPro"
  "cessQueryExitCode_ErrorNotSupportedByPla"
  "tform\020\373\377\377\377\377\377\377\377\377\001*\362\001\n EWindowsUpdateInsta"
  "llationImpact\0227\n*k_EWindowsUpdateInstall"
  "ationImpact_Unknown\020\377\377\377\377\377\377\377\377\377\001\022-\n)k_EWin"
  "dowsUpdateInstallationImpact_Normal\020\000\022,\n"
  "(k_EWindowsUpdateInstallationImpact_Mino"
  "r\020\001\0228\n4k_EWindowsUpdateInstallationImpac"
  "t_ExclusiveHandling\020\002*\362\001\n\034EWindowsUpdate"
  "RebootBehavior\0223\n&k_EWindowsUpdateReboot"
  "Behavior_Unknown\020\377\377\377\377\377\377\377\377\377\001\0223\n/k_EWindow"
  "sUpdateRebootBehavior_NeverNeedsReboot\020\000"
  "\0224\n0k_EWindowsUpdateRebootBehavior_Alway"
  "sNeedsReboot\020\001\0222\n.k_EWindowsUpdateReboot"
  "Behavior_MightNeedReboot\020\002*\376\001\n\026EExternal"
  "SaleEventType\022$\n k_EExternalSaleEventTyp"
  "e_Unknown\020\000\022&\n\"k_EExternalSaleEventType_"
  "Publisher\020\001\022%\n!k_EExternalSaleEventType_"
  "Showcase\020\002\022#\n\037k_EExternalSaleEventType_R"
  "egion\020\003\022\"\n\036k_EExternalSaleEventType_Them"
  "e\020\004\022&\n\"k_EExternalSaleEventType_Franchis"
  "e\020\005*\333\001\n\037EEnhancedMarketAppearanceStatus\022"
  ")\n%k_EnhancedMarketAppearanceStatus_None"
  "\020\000\022,\n(k_EnhancedMarketAppearanceStatus_P"
  "ending\020\001\022/\n+k_EnhancedMarketAppearanceSt"
  "atus_InProgress\020\002\022.\n*k_EnhancedMarketApp"
  "earanceStatus_Completed\020\003*\363\002\n\031EContentRe"
  "portSubjectType\022\'\n#k_EContentReportSubje"
  "ctType_Invalid\020\000\022)\n%k_EContentReportSubj"
  "ectType_ForumPost\020\001\022-\n)k_EContentReportS"
  "ubjectType_CommentThread\020\002\022\'\n#k_EContent"
  "ReportSubjectType_UGCFile\020\003\022-\n)k_EConten"
  "tReportSubjectType_FriendChatMsg\020\004\022+\n\'k_"
  "EContentReportSubjectType_ChatRoomMsg\020\005\022"
  ")\n%k_EContentReportSubjectType_ChatGroup"
  "\020\006\022#\n\037k_EContentReportSubjectType_MAX\020\007*"
  "\331\001\n\036EControlledLegalCategoryStatus\022)\n%k_"
  "EControlledLegalCategoryStatus_None\020\000\022,\n"
  "(k_EControlledLegalCategoryStatus_Accuse"
  "d\020\001\022.\n*k_EControlledLegalCategoryStatus_"
  "Convicted\020\002\022.\n*k_EControlledLegalCategor"
  "yStatus_Acquitted\020\003*\251\001\n\026EContentModerato"
  "rLevel\022 \n\034k_EContentModeratorLevel_Any\020\000"
  "\022\'\n#k_EContentModeratorLevel_Supervisor\020"
  "\001\022\"\n\036k_EContentModeratorLevel_Valve\020\n\022 \n"
  "\034k_EContentModeratorLevel_MAX\020\013*\313\006\n\030ECon"
  "tentReportResolution\022)\n%k_EContentReport"
  "Resolution_Unresolved\020\000\022(\n$k_EContentRep"
  "ortResolution_Acquitted\020\001\022&\n\"k_EContentR"
  "eportResolution_Removed\020\002\022)\n%k_EContentR"
  "eportResolution_Relabelled\020\003\022)\n%k_EConte"
  "ntReportResolution_Suspicious\020\004\022/\n+k_ECo"
  "ntentReportResolution_HarassmentStrike\020\005"
  "\022%\n!k_EContentReportResolution_Purged\020\006\022"
  "2\n.k_EContentReportResolution_Disconnect"
  "edFromApp\020\007\022:\n6k_EContentReportResolutio"
  "n_SuspiciousIncludingUpvoters\020\010\0220\n,k_ECo"
  "ntentReportResolution_VisibilityChanged\020"
  "\t\0229\n5k_EContentReportResolution_CountryR"
  "estrictionsChanged\020\n\022,\n(k_EContentReport"
  "Resolution_RemoveAndWarn\020\013\022+\n\'k_EContent"
  "ReportResolution_RemoveAndBan\020\014\022,\n(k_ECo"
  "ntentReportResolution_RemoveAndKick\020\r\022)\n"
  "%k_EContentReportResolution_Sanctioned\020\016"
  "\022(\n$k_EContentReportResolution_Sustained"
  "\020\017\022%\n!k_EContentReportResolution_Broken\020"
  "\020\022\"\n\036k_EContentReportResolution_MAX\020\021*\246\005"
  "\n\032EContentModerationSanction\022(\n$k_EConte"
  "ntModerationSanction_Invalid\020\000\022(\n$k_ECon"
  "tentModerationSanction_Deleted\020\001\0220\n,k_EC"
  "ontentModerationSanction_CommunityBanned"
  "\020\002\022*\n&k_EContentModerationSanction_HubBa"
  "nned\020\003\022,\n(k_EContentModerationSanction_T"
  "radeBanned\020\004\0226\n2k_EContentModerationSanc"
  "tion_CommentHistoryDeleted\020\005\022+\n\'k_EConte"
  "ntModerationSanction_Relabelled\020\006\0221\n-k_E"
  "ContentModerationSanction_MarkAsSuspicio"
  "us\020\007\022\'\n#k_EContentModerationSanction_War"
  "ned\020\010\0220\n,k_EContentModerationSanction_Ki"
  "ckedFromGroup\020\t\0221\n-k_EContentModerationS"
  "anction_HarassmentBanned\020\n\0221\n-k_EContent"
  "ModerationSanction_HarassmentStrike\020\013\022)\n"
  "%k_EContentModerationSanction_Escalate\020\014"
  "\022$\n k_EContentModerationSanction_MAX\020\r*\377"
  "\010\n\033EContentReportSubjectAction\022)\n%k_ECon"
  "tentReportSubjectAction_Invalid\020\000\022,\n(k_E"
  "ContentReportSubjectAction_Unresolved\020\001\022"
  ",\n(k_EContentReportSubjectAction_Sanctio"
  "ned\020\002\022+\n\'k_EContentReportSubjectAction_A"
  "cquitted\020\003\022+\n\'k_EContentReportSubjectAct"
  "ion_Cancelled\020\004\022)\n%k_EContentReportSubje"
  "ctAction_Updated\020\005\022+\n\'k_EContentReportSu"
  "bjectAction_Escalated\020\006\022*\n&k_EContentRep"
  "ortSubjectAction_Disputed\020\007\022+\n\'k_EConten"
  "tReportSubjectAction_Sustained\020\010\022(\n$k_EC"
  "ontentReportSubjectAction_Locked\020\t\022*\n&k_"
  "EContentReportSubjectAction_Unlocked\020\n\022)"
  "\n%k_EContentReportSubjectAction_Deleted\020"
  "\013\022(\n$k_EContentReportSubjectAction_Warne"
  "d\020\014\022/\n+k_EContentReportSubjectAction_Ban"
  "nedFromHub\020\r\0225\n1k_EContentReportSubjectA"
  "ction_BannedFromCommunity\020\016\022-\n)k_EConten"
  "tReportSubjectAction_TradeBanned\020\017\0224\n0k_"
  "EContentReportSubjectAction_MarkedAsSusp"
  "icious\020\020\022.\n*k_EContentReportSubjectActio"
  "n_ResetContent\020\021\0222\n.k_EContentReportSubj"
  "ectAction_EscalatedForCSAM\020\022\0227\n3k_EConte"
  "ntReportSubjectAction_EscalatedForTerror"
  "ism\020\023\022)\n%k_EContentReportSubjectAction_C"
  "laimed\020\024\022*\n&k_EContentReportSubjectActio"
  "n_Released\020\025\0221\n-k_EContentReportSubjectA"
  "ction_PrivateMessaged\020\026\022/\n+k_EContentRep"
  "ortSubjectAction_OwnerDisputed\020\027*\211\032\n\024ECo"
  "ntentReportReason\022\"\n\036k_EContentReportRea"
  "son_Invalid\020\000\022\037\n\033k_EContentReportReason_"
  "None\020\001\022\"\n\036k_EContentReportReason_Unknown"
  "\020\002\022%\n!k_EContentReportReason_Harassment\020"
  "\003\0222\n.k_EContentReportReason_BullyingAndI"
  "ntimidation\020\004\022#\n\037k_EContentReportReason_"
  "Stalking\020\005\022\"\n\036k_EContentReportReason_Dox"
  "xing\020\006\022*\n&k_EContentReportReason_OtherHa"
  "rassment\020\007\022.\n*k_EContentReportReason_Enc"
  "ouragingViolence\020\010\022.\n*k_EContentReportRe"
  "ason_EncouragingSelfHarm\020\t\022-\n)k_EContent"
  "ReportReason_EncouragingSuicide\020\n\0222\n.k_E"
  "ContentReportReason_OtherViolenceOrSelfH"
  "arm\020\013\0221\n-k_EContentReportReason_Phishing"
  "OrAccountTheft\020\014\022,\n(k_EContentReportReas"
  "on_AttemptedScamming\020\r\0224\n0k_EContentRepo"
  "rtReason_LinkingToMaliciousContent\020\016\022(\n$"
  "k_EContentReportReason_Impersonation\020\017\022-"
  "\n)k_EContentReportReason_OtherScamsAndTh"
  "eft\020\020\022/\n+k_EContentReportReason_Encourag"
  "ingTerrorism\020\021\022.\n*k_EContentReportReason"
  "_OrganizingTerrorism\020\022\022)\n%k_EContentRepo"
  "rtReason_OtherTerrorism\020\023\022(\n$k_EContentR"
  "eportReason_TargetedAbuse\020\024\022+\n\'k_EConten"
  "tReportReason_NamingAndShaming\020\025\022)\n%k_EC"
  "ontentReportReason_Discrimination\020\026\022%\n!k"
  "_EContentReportReason_OtherAbuse\020\027\022#\n\037k_"
  "EContentReportReason_Trolling\020\030\022\"\n\036k_ECo"
  "ntentReportReason_Baiting\020\031\022$\n k_EConten"
  "tReportReason_Derailing\020\032\022*\n&k_EContentR"
  "eportReason_OtherDisruptive\020\033\022\037\n\033k_ECont"
  "entReportReason_Spam\020\034\022\"\n\036k_EContentRepo"
  "rtReason_Begging\020\035\022$\n k_EContentReportRe"
  "ason_Reposting\020\036\022(\n$k_EContentReportReas"
  "on_OtherOffTopic\020\037\022,\n(k_EContentReportRe"
  "ason_CSAMSexualContent\020 \0223\n/k_EContentRe"
  "portReason_CSAMGroomingOrEnticement\020!\022$\n"
  " k_EContentReportReason_CSAMOther\020\"\0220\n,k"
  "_EContentReportReason_NudityOrSexualCont"
  "ent\020#\0220\n,k_EContentReportReason_NonConse"
  "nsualMaterial\020$\022&\n\"k_EContentReportReaso"
  "n_Advertising\020%\022(\n$k_EContentReportReaso"
  "n_ReferralLinks\020&\022#\n\037k_EContentReportRea"
  "son_Gambling\020\'\022\"\n\036k_EContentReportReason"
  "_Raffles\020(\0222\n.k_EContentReportReason_Oth"
  "erCommercialActivity\020)\022,\n(k_EContentRepo"
  "rtReason_InauthenticReview\020*\022G\nCk_EConte"
  "ntReportReason_HiddenAdvertisementOrComm"
  "ercialCommunication\020+\022D\n@k_EContentRepor"
  "tReason_MisleadingInformationAboutGoodsO"
  "rServices\020,\022C\n\?k_EContentReportReason_Mi"
  "sleadingInformationAboutConsumerRights\020-"
  "\022>\n:k_EContentReportReason_Noncompliance"
  "WithPricingRegulations\020.\0226\n2k_EContentRe"
  "portReason_RightToBeForgottenViolation\020/"
  "\0229\n5k_EContentReportReason_MissingProces"
  "singGroundForData\0200\022A\n=k_EContentReportR"
  "eason_OtherDataProtectionAndPrivacyViola"
  "tion\0201\022-\n)k_EContentReportReason_Gendere"
  "dHarassment\0202\022:\n6k_EContentReportReason_"
  "GenderedBullyingAndIntimidation\0203\022+\n\'k_E"
  "ContentReportReason_GenderedStalking\0204\022*"
  "\n&k_EContentReportReason_GenderedDoxxing"
  "\0205\0222\n.k_EContentReportReason_GenderedOth"
  "erHarassment\0206\0226\n2k_EContentReportReason"
  "_GenderedEncouragingViolence\0207\0220\n,k_ECon"
  "tentReportReason_GenderedTargetedAbuse\0208"
  "\0221\n-k_EContentReportReason_CSAMFakedSexu"
  "alContent\0209\0228\n4k_EContentReportReason_Ge"
  "nderedNonConsensualMaterial\020:\022=\n9k_ECont"
  "entReportReason_FakedGenderedNonConsensu"
  "alMaterial\020;\0225\n1k_EContentReportReason_F"
  "akedNonConsensualMaterial\020<\022\?\n;k_EConten"
  "tReportReason_NegativeEffectonDiscourseO"
  "rElections\020=\0221\n-k_EContentReportReason_Q"
  "uotesModeratedContent\020>\0223\n/k_EContentRep"
  "ortReason_CredibleThreatOfViolence\020\?\0222\n."
  "k_EContentReportReason_AutoCreatedOnMode"
  "ration\020@\022!\n\035k_EContentReportReason_Pirac"
  "y\020A\022\'\n#k_EContentReportReason_ToSViolati"
  "on\020B\022)\n%k_EContentReportReason_Miscatego"
  "rized\020C\0223\n/k_EContentReportReason_Bypass"
  "ingProfanityFilter\020D\022\036\n\032k_EContentReport"
  "Reason_MAX\020E*\270\001\n\025EResolutionAutomation\022\""
  "\n\036k_EResolutionAutomation_Manual\020\000\022.\n*k_"
  "EResolutionAutomation_PartiallyAutomated"
  "\020\001\022*\n&k_EResolutionAutomation_FullyAutom"
  "ated\020\002\022\037\n\033k_EResolutionAutomation_MAX\020\003*"
  "\223\004\n\022EPressOutletAction\022 \n\034k_EPressOutlet"
  "Action_Invalid\020\000\022 \n\034k_EPressOutletAction"
  "_Granted\020\001\022 \n\034k_EPressOutletAction_Remov"
  "ed\020\002\022 \n\034k_EPressOutletAction_Created\020\003\022 "
  "\n\034k_EPressOutletAction_Updated\020\004\022 \n\034k_EP"
  "ressOutletAction_Deleted\020\005\022\"\n\036k_EPressOu"
  "tletAction_Undeleted\020\006\022\"\n\036k_EPressOutlet"
  "Action_StagedAdd\020\007\022%\n!k_EPressOutletActi"
  "on_StagedDelete\020\010\022%\n!k_EPressOutletActio"
  "n_EnterStaging\020\t\022$\n k_EPressOutletAction"
  "_ExitStaging\020\n\022)\n%k_EPressOutletAction_R"
  "everseStagedAdd\020\013\022,\n(k_EPressOutletActio"
  "n_ReverseStagedDelete\020\014\022\034\n\030k_EPressOutle"
  "tAction_MAX\020\r*\332\001\n\036EPressOutletMemberPend"
  "ingState\022+\n\'k_EPressOutletMemberPendingS"
  "tate_Member\020\000\0221\n-k_EPressOutletMemberPen"
  "dingState_StagedDelete\020\001\022.\n*k_EPressOutl"
  "etMemberPendingState_StagedAdd\020\002\022(\n$k_EP"
  "ressOutletMemberPendingState_MAX\020\003*\232\002\n\024E"
  "CommentDeleteReason\022\"\n\036k_ECommentDeleteR"
  "eason_Invalid\020\000\022\037\n\033k_ECommentDeleteReaso"
  "n_User\020\001\022&\n\"k_ECommentDeleteReason_Threa"
  "dOwner\020\002\022$\n k_ECommentDeleteReason_Moder"
  "ator\020\003\022\"\n\036k_ECommentDeleteReason_Support"
  "\020\004\022\037\n\033k_ECommentDeleteReason_Spam\020\005\022*\n&k"
  "_ECommentDeleteReason_AccountDeletion\020\006"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_enums_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_enums_2eproto = {
  false, false, 28999, descriptor_table_protodef_enums_2eproto, "enums.proto", 
  &descriptor_table_enums_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_enums_2eproto::offsets,
  file_level_metadata_enums_2eproto, file_level_enum_descriptors_enums_2eproto, file_level_service_descriptors_enums_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_enums_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return descriptor_table_enums_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_enums_2eproto(&descriptor_table_enums_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileQueryType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[0];
}
bool EPublishedFileQueryType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileInappropriateProvider_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[1];
}
bool EPublishedFileInappropriateProvider_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileInappropriateResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[2];
}
bool EPublishedFileInappropriateResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 30:
    case 50:
    case 75:
    case 100:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPersonaStateFlag_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[3];
}
bool EPersonaStateFlag_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 4:
    case 8:
    case 256:
    case 512:
    case 1024:
    case 2048:
    case 4096:
    case 8192:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentCheckProvider_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[4];
}
bool EContentCheckProvider_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProfileCustomizationType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[5];
}
bool EProfileCustomizationType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileStorageSystem_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[6];
}
bool EPublishedFileStorageSystem_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECloudStoragePersistState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[7];
}
bool ECloudStoragePersistState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESDCardFormatStage_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[8];
}
bool ESDCardFormatStage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageFormatStage_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[9];
}
bool EStorageFormatStage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemFanControlMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[10];
}
bool ESystemFanControlMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EColorGamutLabelSet_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[11];
}
bool EColorGamutLabelSet_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowStackingOrder_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[12];
}
bool EWindowStackingOrder_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBluetoothDeviceType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[13];
}
bool EBluetoothDeviceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESpeakerConfiguration_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[14];
}
bool ESpeakerConfiguration_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioDirection_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[15];
}
bool ESystemAudioDirection_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioChannel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[16];
}
bool ESystemAudioChannel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioPortType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[17];
}
bool ESystemAudioPortType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioPortDirection_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[18];
}
bool ESystemAudioPortDirection_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemServiceState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[19];
}
bool ESystemServiceState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBluetoothAudioPreference_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[20];
}
bool EBluetoothAudioPreference_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGraphicsPerfOverlayLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[21];
}
bool EGraphicsPerfOverlayLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGPUPerformanceLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[22];
}
bool EGPUPerformanceLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESplitScalingFilter_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[23];
}
bool ESplitScalingFilter_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESplitScalingScaler_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[24];
}
bool ESplitScalingScaler_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGamescopeBlurMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[25];
}
bool EGamescopeBlurMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESLSHelper_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[26];
}
bool ESLSHelper_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHDRVisualization_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[27];
}
bool EHDRVisualization_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHDRToneMapOperator_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[28];
}
bool EHDRToneMapOperator_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECPUGovernor_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[29];
}
bool ECPUGovernor_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EUpdaterType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[30];
}
bool EUpdaterType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EUpdaterState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[31];
}
bool EUpdaterState_IsValid(int value) {
  switch (value) {
    case 0:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageBlockContentType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[32];
}
bool EStorageBlockContentType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageBlockFileSystemType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[33];
}
bool EStorageBlockFileSystemType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageDriveMediaType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[34];
}
bool EStorageDriveMediaType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemDisplayCompatibilityMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[35];
}
bool ESystemDisplayCompatibilityMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamOSCompatibilityCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[36];
}
bool ESteamOSCompatibilityCategory_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamOSCompatibilityResultDisplayType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[37];
}
bool ESteamOSCompatibilityResultDisplayType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[38];
}
bool ESteamDeckCompatibilityCategory_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityResultDisplayType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[39];
}
bool ESteamDeckCompatibilityResultDisplayType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityTestResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[40];
}
bool ESteamDeckCompatibilityTestResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EACState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[41];
}
bool EACState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBatteryState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[42];
}
bool EBatteryState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EOSBranch_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[43];
}
bool EOSBranch_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBrowserGPUStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[44];
}
bool EBrowserGPUStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBrowserFeatureStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[45];
}
bool EBrowserFeatureStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGpuDriverId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[46];
}
bool EGpuDriverId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECommunityItemClass_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[47];
}
bool ECommunityItemClass_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityFeedback_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[48];
}
bool ESteamDeckCompatibilityFeedback_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProvideDeckFeedbackPreference_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[49];
}
bool EProvideDeckFeedbackPreference_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHardwareCompatibilityFeedbackDetails_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[50];
}
bool EHardwareCompatibilityFeedbackDetails_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGameFrameRateReportingPreference_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[51];
}
bool EGameFrameRateReportingPreference_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ETouchGesture_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[52];
}
bool ETouchGesture_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESessionPersistence_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[53];
}
bool ESessionPersistence_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ENewSteamAnnouncementState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[54];
}
bool ENewSteamAnnouncementState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EForumType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[55];
}
bool EForumType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECommentThreadType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[56];
}
bool ECommentThreadType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBroadcastPermission_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[57];
}
bool EBroadcastPermission_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBroadcastEncoderSetting_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[58];
}
bool EBroadcastEncoderSetting_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECloudGamingPlatform_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[59];
}
bool ECloudGamingPlatform_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECompromiseDetectionType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[60];
}
bool ECompromiseDetectionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAsyncGameSessionUserState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[61];
}
bool EAsyncGameSessionUserState_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAsyncGameSessionUserVisibility_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[62];
}
bool EAsyncGameSessionUserVisibility_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGameRecordingType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[63];
}
bool EGameRecordingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGRMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[64];
}
bool EGRMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EExportCodec_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[65];
}
bool EExportCodec_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProtoAppType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[66];
}
bool EProtoAppType_IsValid(int value) {
  switch (value) {
    case -2147483647 - 1:
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
    case 128:
    case 256:
    case 512:
    case 1024:
    case 2048:
    case 4096:
    case 8192:
    case 16384:
    case 32768:
    case 65536:
    case 1073741824:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAppTestType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[67];
}
bool EAppTestType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EChildProcessQueryExitCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[68];
}
bool EChildProcessQueryExitCode_IsValid(int value) {
  switch (value) {
    case -5:
    case -4:
    case -3:
    case -2:
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowsUpdateInstallationImpact_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[69];
}
bool EWindowsUpdateInstallationImpact_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowsUpdateRebootBehavior_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[70];
}
bool EWindowsUpdateRebootBehavior_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EExternalSaleEventType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[71];
}
bool EExternalSaleEventType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EEnhancedMarketAppearanceStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[72];
}
bool EEnhancedMarketAppearanceStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportSubjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[73];
}
bool EContentReportSubjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EControlledLegalCategoryStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[74];
}
bool EControlledLegalCategoryStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentModeratorLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[75];
}
bool EContentModeratorLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportResolution_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[76];
}
bool EContentReportResolution_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentModerationSanction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[77];
}
bool EContentModerationSanction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportSubjectAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[78];
}
bool EContentReportSubjectAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[79];
}
bool EContentReportReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EResolutionAutomation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[80];
}
bool EResolutionAutomation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPressOutletAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[81];
}
bool EPressOutletAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPressOutletMemberPendingState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[82];
}
bool EPressOutletMemberPendingState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECommentDeleteReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[83];
}
bool ECommentDeleteReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
